### ISSUE TITLE
Issue with version 0.24.1

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#527]
When using Swarmion version 0.24.1:
```
2023-02-10T19:11:12.393Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.main is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.main is undefined or not exported",
        "    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1038:15)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}
```

**Comment by fargito** [comment]
I'm trying to pinpoint the issue in this release...

We definitely need to add integration tests for our packages on actual AWS environment 🙄

**Comment by fargito** [comment]
Ok so apparently it comes from https://github.com/swarmion/swarmion/commit/08019e8e6f66b656f2ff33c45feda2abb1769528

**Comment by fargito** [comment]
This is due to:
https://github.com/swarmion/swarmion/commit/08019e8e6f66b656f2ff33c45feda2abb1769528#diff-5bab8e38aa0a5de5269ee0e1e12525d234ed42a0894fdee17edef4f9fd9928bbR10-R11

This looks like a circular import issue, maybe our circular tests configuration is wrong...

**Comment by fargito** [comment]
I'm really lost here...

In order to have a working release, I'll temporarily remove the two lines (so #461 is no longer available). @Sc0ra we'll need to work to get it back online 🏋🏻‍♂️

**Comment by fargito** [comment]
In order to fully fix this issue, we need to:
- bring back the mock handler feature
- add integration tests to ensure this never happens again

**Comment by fargito** [comment]
Ok I think I have the culprit: it is probably `json-schema-faker`. My current hypothesis is that it is not side-effects-free, so it interferes with the code shipped on the Lambda.

@Sc0ra @adriencaccia  I think the best way is to create a separate package for testing (`serverless-contracts-tests`?). This way we can keep the value of this package without shipping it on Lambda.

WDYT?

**Comment by fargito** [comment]
I completely agree with this. We need to split `serverless-contracts` to ensure it remains scalable.

This my be a breaking change though, we'll need to have a migration strategy as well...

**Comment by fargito** [comment]
Getting some progress on the resolution: Removing this single line from the bundled lambda code fixes the issue:

```diff
// ../../node_modules/.pnpm/json-schema-faker@0.5.0-rcv.46/node_modules/json-schema-faker/dist/vendor.js
(function(f) {
  if (typeof exports === "object" && typeof module !== "undefined") {
-    module.exports = f();
  } else if (typeof define === "function" && define.amd) {
    define([], f);
  } else {
    var g;
    if (typeof window !== "undefined") {
      g = window;
    } else if (typeof global !== "undefined") {
      g = global;
    } else if (typeof self !== "undefined") {
      g = self;
    } else {
      g = this;
    }
    g.$RefParser = f();
  }
```

This confirms this issue comes from the inclusion of `json-schema-faker` in the bundle

**Comment by fargito** [comment]
However, two questions remain:
1. why is this piece of code included in our bundle?
2. why is it overriding `module.exports`?

**Comment by adriencaccia** [comment]
It might be worth to open an issue on the `json-schema-faker` repository

**Comment by adriencaccia** [comment]
We can resolve this using something similar to what I talked about in https://github.com/swarmion/swarmion/issues/551#issuecomment-1479385043

Ie. using `exports` to only expose tests related helpers through a subpath.

WDYT @fargito?
