### ISSUE TITLE
@swarmion/nx-plugin:cdk-service creates broken cdk bootstraps 

### ISSUE THREAD

**Issue by CorentinDoue** [swarmion/swarmion#615]
### Describe the bug

using `nx generate @swarmion/nx-plugin:cdk-service nft-dummy`, the generated service contains some scripts to bootstrap the CDK

```json
{
 "scripts": {
    "bootstrap": "cdk bootstrap --profile swarmion-developer --qualifier s_8swf03cp",
    "bootstrap-production": "cdk bootstrap --context stage=production --qualifier s_8swf03cp",
    "bootstrap-staging": "cdk bootstrap --context stage=staging --qualifier s_8swf03cp",
  }
}
```

the qualifier is built from a hash of the project name 
https://github.com/swarmion/swarmion/blob/27cdea8249c2c122b2ff078260c7ba92c702ab78/packages/nx-plugin/src/generators/cdk-service/typed-json-config/package.json.ts#L9
https://github.com/swarmion/swarmion/blob/7b8edcb1b713b12664b602ab18b35296ce1f9dd1/packages/nx-plugin/src/generators/helpers/normalizeOptions.ts#L35-L39
This hash can contain characters that are not supported as qualifier such `_`

=> The bootstrap fails 💥

```
❯ pnpn run bootstrap

> @swarmion/nft-dummy@1.0.0 bootstrap /Users/cdoue/www-dev/projects/swarmion/services/nft-dummy
> cdk bootstrap --profile swarmion-developer --qualifier s_8swf03cp

 ⏳  Bootstrapping environment aws://032062562436/eu-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkitNftDummy: creating CloudFormation changeset...
 ❌  Environment aws://032062562436/eu-west-1 failed bootstrapping: Error [ValidationError]: Template format error: Output FileAssetKeyArn is malformed. The Name field of every Export member must be specified and consist only of alphanumeric characters, colons, or hyphens.
    at Request.extractError (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:46127)
    at Request.callListeners (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:88989)
    at Request.emit (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:88437)
    at Request.emit (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:194844)
    at Request.transition (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:188396)
    at AcceptorStateMachine.runTo (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:153268)
    at /Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:153598
    at Request.<anonymous> (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:188688)
    at Request.<anonymous> (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:194919)
    at Request.callListeners (/Users/cdoue/www-dev/projects/swarmion/node_modules/.pnpm/aws-cdk@2.73.0/node_modules/aws-cdk/lib/index.js:275:89157) {
  code: 'ValidationError',
  time: 2023-04-07T14:56:05.535Z,
  requestId: '89036b53-56ce-4c4a-b7da-e221f653c59b',
  statusCode: 400,
  retryable: false,
  retryDelay: 623.5548680046232
}

Template format error: Output FileAssetKeyArn is malformed. The Name field of every Export member must be specified and consist only of alphanumeric characters, colons, or hyphens.
 ELIFECYCLE  Command failed with exit code 1.

```

### Reproduction

```sh
nx generate @swarmion/nx-plugin:cdk-service nft-dummy
cd services/nft-dummy
pnpm run bootstrap
```

### System Info

```shell
sh: envinfo: command not found
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/swarmion/swarmion/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.swarmion.dev/docs/).
- [X] Check that there isn't [already an issue](https://github.com/swarmion/swarmion/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by adriencaccia** [comment]
Nice catch @CorentinDoue 

I already had a problem with uppercase letters and did https://github.com/swarmion/swarmion/commit/2604d0241e22a7d80f6c90e4d66031920dcbba7e to fix it, but let's continue to restrict characters 😬
