### ISSUE TITLE
Improvement to failure error message

### ISSUE THREAD

**Issue by ktwbc** [swarmion/swarmion#659]
### Clear and concise description of the problem

When using getHandlerPath() in serverless-helper with a filename specified, having a filename that does not exist will crash compile (as would be expected). But it would be helpful if a better descriptive error could be output. For example, this line where you can specify a filename:

const config: LambdaFunction = {
  environment: {},
  handler: getHandlerPath(__dirname, { fileName: 'invalid-file.ts' }),

Will result in output from compile 
```
Error: Compilation failed. Please ensure you have an index file with ext .ts or .js, or have a path listed as main key in package.json
    at /Volumes/dev/stack/node_modules/.pnpm/serverless-esbuild@1.45.0_esbuild@0.17.19/node_modules/serverless-esbuild/src/helper.ts:93:11
    at Array.map (<anonymous>)
    at extractFunctionEntries (/Volumes/dev/stack/node_modules/.pnpm/serverless-esbuild@1.45.0_esbuild@0.17.19/node_modules/serverless-esbuild/src/helper.ts:57:33)
(rest of stack trace)
```

### Suggested solution

It would be much better if the compile could error out with something like

'invalid-file.ts' not found by getHandlerPath() in Volumes/dev/stack/services/myservice/myfunction/config.ts

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/swarmion/swarmion/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.swarmion.dev/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Sc0ra** [comment]
Hello @ktwbc 

Thank you for opening an issue
I will try to look on this problem tomorrow !
